name: 'Configure AWS'
description: 'Configures AWS credentials, authenticates to ECR and creates AWS profile'

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'The region on AWS to host the workspace resources in'
    required: true
  eks_cluster:
    description: 'The name of the EKS cluster on AWS'
    required: true
outputs:
  registry_url:
    description: 'The URL of the Container Registry in AWS'
    value: ${{ steps.construct_registry_url.outputs.registry_url }}

runs:
  using: "composite"
  steps:
    # Configure AWS credentials
    - name: Configure AWS credentials
      id: configure_aws_credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    # Configure authentication to ECR
    - name: Authenticate to ECR
      uses: jwalton/gh-ecr-login@v1
      with:
        access-key-id: ${{ inputs.aws_access_key_id }}
        secret-access-key: ${{ inputs.aws_secret_access_key }}
        region: ${{ inputs.aws_region }}

    # Create profile for AWS interface
    - name: Create the default profile for EKS/ECR interface
      run: |-
        aws configure set aws_access_key_id ${{ inputs.aws_access_key_id }}
        aws configure set aws_secret_access_key ${{ inputs.aws_secret_access_key }}
      shell: bash

    # Construct the ECR registry URL
    - name: Construct ECR Registry URL
      id: construct_registry_url
      run: |-
        registry_url="${{ steps.configure_aws_credentials.outputs.aws-account-id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com"
        echo "registry_url=$registry_url" >> $GITHUB_ENV
        echo "::set-output name=registry_url::$registry_url"
      shell: bash

    # Update kube-config for EKS cluster
    - name: Config kubectl
      run: |-
        # Update kube-config for EKS cluster
        aws eks --region ${{ inputs.aws_region }} update-kubeconfig --name ${{ inputs.eks_cluster }}
      shell: bash
